// Gerado a partir de discovery/output/modelos/ — F2.
// 72 incremental | 5 snapshot | 2 estatico.
export type SyncMode = "incremental" | "snapshot" | "estatico";

export interface CatalogEntry {
  odooModel: string;
  mode: SyncMode;
}

export const MODEL_CATALOG: readonly CatalogEntry[] = [
  { odooModel: "contabil.conta", mode: "incremental" },
  { odooModel: "contabil.conta.referencial", mode: "incremental" },
  { odooModel: "estoque.extrato", mode: "snapshot" },
  { odooModel: "estoque.extrato.rastreabilidade", mode: "incremental" },
  { odooModel: "estoque.local", mode: "incremental" },
  { odooModel: "estoque.saldo", mode: "incremental" },
  { odooModel: "estoque.saldo.hoje", mode: "snapshot" },
  { odooModel: "estoque.saldo.hoje.duracao.dias", mode: "snapshot" },
  { odooModel: "estoque.saldo.rastreabilidade", mode: "incremental" },
  { odooModel: "estoque.saldo.rastreabilidade.hoje", mode: "snapshot" },
  { odooModel: "finan.banco", mode: "incremental" },
  { odooModel: "finan.banco.extrato", mode: "incremental" },
  { odooModel: "finan.banco.saldo", mode: "incremental" },
  { odooModel: "finan.banco.saldo.hoje", mode: "snapshot" },
  { odooModel: "finan.carteira", mode: "incremental" },
  { odooModel: "finan.centro.resultado", mode: "incremental" },
  { odooModel: "finan.conta", mode: "incremental" },
  { odooModel: "finan.documento", mode: "incremental" },
  { odooModel: "finan.fluxo.caixa", mode: "incremental" },
  { odooModel: "finan.forma.pagamento", mode: "incremental" },
  { odooModel: "finan.lancamento", mode: "incremental" },
  { odooModel: "finan.lancamento.item", mode: "incremental" },
  { odooModel: "finan.pagamento.divida", mode: "incremental" },
  { odooModel: "finan.remessa", mode: "incremental" },
  { odooModel: "finan.remessa.item", mode: "incremental" },
  { odooModel: "finan.retorno", mode: "incremental" },
  { odooModel: "finan.retorno.item", mode: "incremental" },
  { odooModel: "finan.tipo.faturamento", mode: "incremental" },
  { odooModel: "pedido.documento", mode: "incremental" },
  { odooModel: "pedido.documento.historico", mode: "incremental" },
  { odooModel: "pedido.documento.historico.tempo", mode: "estatico" },
  { odooModel: "pedido.etapa", mode: "incremental" },
  { odooModel: "pedido.operacao", mode: "incremental" },
  { odooModel: "pedido.operacao.derivada", mode: "incremental" },
  { odooModel: "pedido.parcela", mode: "incremental" },
  { odooModel: "producao.processo", mode: "incremental" },
  { odooModel: "res.company", mode: "incremental" },
  { odooModel: "res.partner", mode: "incremental" },
  { odooModel: "res.users", mode: "incremental" },
  { odooModel: "sped.apuracao.inventario", mode: "incremental" },
  { odooModel: "sped.apuracao.inventario.local", mode: "incremental" },
  { odooModel: "sped.atualizacao.preco", mode: "incremental" },
  { odooModel: "sped.atualizacao.preco.item", mode: "incremental" },
  { odooModel: "sped.atualizacao.preco.regra", mode: "incremental" },
  { odooModel: "sped.dfe.importacao", mode: "incremental" },
  { odooModel: "sped.documento", mode: "incremental" },
  { odooModel: "sped.documento.duplicata", mode: "incremental" },
  { odooModel: "sped.documento.item", mode: "incremental" },
  { odooModel: "sped.documento.item.declaracao.importacao", mode: "incremental" },
  { odooModel: "sped.documento.item.rastreabilidade", mode: "incremental" },
  { odooModel: "sped.documento.item.rateio", mode: "incremental" },
  { odooModel: "sped.documento.modelo.fiscal", mode: "incremental" },
  { odooModel: "sped.documento.pagamento", mode: "incremental" },
  { odooModel: "sped.documento.rateio", mode: "incremental" },
  { odooModel: "sped.documento.referenciado", mode: "incremental" },
  { odooModel: "sped.documento.volume", mode: "incremental" },
  { odooModel: "sped.empresa", mode: "incremental" },
  { odooModel: "sped.endereco", mode: "incremental" },
  { odooModel: "sped.faturamento.simples", mode: "incremental" },
  { odooModel: "sped.operacao", mode: "incremental" },
  { odooModel: "sped.operacao.item", mode: "incremental" },
  { odooModel: "sped.participante", mode: "incremental" },
  { odooModel: "sped.participante.perfil", mode: "incremental" },
  { odooModel: "sped.participante.segmento", mode: "incremental" },
  { odooModel: "sped.produto", mode: "incremental" },
  { odooModel: "sped.produto.controle", mode: "incremental" },
  { odooModel: "sped.produto.familia", mode: "incremental" },
  { odooModel: "sped.produto.lista.material", mode: "incremental" },
  { odooModel: "sped.produto.lista.material.item", mode: "incremental" },
  { odooModel: "sped.produto.lista.material.processo", mode: "incremental" },
  { odooModel: "sped.produto.lote.serie", mode: "incremental" },
  { odooModel: "sped.produto.marca", mode: "incremental" },
  { odooModel: "sped.produto.tipo", mode: "incremental" },
  { odooModel: "sped.produto.variante", mode: "estatico" },
  { odooModel: "sped.produto.volume", mode: "incremental" },
  { odooModel: "sped.usuario", mode: "incremental" },
  { odooModel: "sped.usuario.departamento", mode: "incremental" },
  { odooModel: "sped.usuario.perfil", mode: "incremental" },
  { odooModel: "sped.veiculo", mode: "incremental" },
] as const;

/** Nome da tabela raw de um modelo Odoo: estoque.saldo.hoje -> raw_estoque_saldo_hoje. */
export function rawTableFor(odooModel: string): string {
  return "raw_" + odooModel.replace(/\./g, "_");
}
