// Gerado a partir de discovery/output/modelos/ — F2.
// 107 incremental | 5 snapshot | 2 estatico.
export type SyncMode = "incremental" | "snapshot" | "estatico";

export interface CatalogEntry {
  odooModel: string;
  mode: SyncMode;
  /** Campos que NÃO devem ser copiados para o cache (segredos, blobs).
   * `getModelFields` os subtrai. Vazio/ausente = comportamento padrão. */
  excludeFields?: readonly string[];
}

export const MODEL_CATALOG: readonly CatalogEntry[] = [
  { odooModel: "contabil.conta", mode: "incremental" },
  { odooModel: "contabil.conta.referencial", mode: "incremental" },
  { odooModel: "estoque.extrato", mode: "snapshot" },
  { odooModel: "estoque.extrato.rastreabilidade", mode: "incremental" },
  { odooModel: "estoque.local", mode: "incremental" },
  { odooModel: "estoque.saldo", mode: "incremental" },
  { odooModel: "estoque.saldo.hoje", mode: "snapshot" },
  { odooModel: "estoque.saldo.hoje.duracao.dias", mode: "snapshot" },
  { odooModel: "estoque.saldo.rastreabilidade", mode: "incremental" },
  { odooModel: "estoque.saldo.rastreabilidade.hoje", mode: "snapshot" },
  { odooModel: "finan.banco", mode: "incremental" },
  { odooModel: "finan.banco.extrato", mode: "incremental" },
  { odooModel: "finan.banco.saldo", mode: "incremental" },
  { odooModel: "finan.banco.saldo.hoje", mode: "snapshot" },
  { odooModel: "finan.carteira", mode: "incremental" },
  { odooModel: "finan.centro.resultado", mode: "incremental" },
  { odooModel: "finan.conta", mode: "incremental" },
  { odooModel: "finan.documento", mode: "incremental" },
  { odooModel: "finan.fluxo.caixa", mode: "incremental" },
  { odooModel: "finan.forma.pagamento", mode: "incremental" },
  { odooModel: "finan.lancamento", mode: "incremental" },
  { odooModel: "finan.lancamento.item", mode: "incremental" },
  { odooModel: "finan.pagamento.divida", mode: "incremental" },
  { odooModel: "finan.remessa", mode: "incremental" },
  { odooModel: "finan.remessa.item", mode: "incremental" },
  { odooModel: "finan.retorno", mode: "incremental" },
  { odooModel: "finan.retorno.item", mode: "incremental" },
  { odooModel: "finan.tipo.faturamento", mode: "incremental" },
  { odooModel: "pedido.documento", mode: "incremental" },
  { odooModel: "pedido.documento.historico", mode: "incremental" },
  { odooModel: "pedido.documento.historico.tempo", mode: "estatico" },
  { odooModel: "pedido.etapa", mode: "incremental" },
  { odooModel: "pedido.operacao", mode: "incremental" },
  { odooModel: "pedido.operacao.derivada", mode: "incremental" },
  { odooModel: "pedido.parcela", mode: "incremental" },
  { odooModel: "producao.processo", mode: "incremental" },
  { odooModel: "res.company", mode: "incremental" },
  { odooModel: "res.partner", mode: "incremental" },
  { odooModel: "res.users", mode: "incremental" },
  { odooModel: "sped.apuracao.inventario", mode: "incremental" },
  { odooModel: "sped.apuracao.inventario.local", mode: "incremental" },
  { odooModel: "sped.atualizacao.preco", mode: "incremental" },
  { odooModel: "sped.atualizacao.preco.item", mode: "incremental" },
  { odooModel: "sped.atualizacao.preco.regra", mode: "incremental" },
  { odooModel: "sped.dfe.importacao", mode: "incremental" },
  { odooModel: "sped.documento", mode: "incremental" },
  { odooModel: "sped.documento.duplicata", mode: "incremental" },
  { odooModel: "sped.documento.item", mode: "incremental" },
  { odooModel: "sped.documento.item.declaracao.importacao", mode: "incremental" },
  { odooModel: "sped.documento.item.rastreabilidade", mode: "incremental" },
  { odooModel: "sped.documento.item.rateio", mode: "incremental" },
  { odooModel: "sped.documento.modelo.fiscal", mode: "incremental" },
  { odooModel: "sped.documento.pagamento", mode: "incremental" },
  { odooModel: "sped.documento.rateio", mode: "incremental" },
  { odooModel: "sped.documento.referenciado", mode: "incremental" },
  { odooModel: "sped.documento.volume", mode: "incremental" },
  { odooModel: "sped.empresa", mode: "incremental" },
  { odooModel: "sped.endereco", mode: "incremental" },
  { odooModel: "sped.faturamento.simples", mode: "incremental" },
  { odooModel: "sped.operacao", mode: "incremental" },
  { odooModel: "sped.operacao.item", mode: "incremental" },
  { odooModel: "sped.participante", mode: "incremental" },
  { odooModel: "sped.participante.perfil", mode: "incremental" },
  { odooModel: "sped.participante.segmento", mode: "incremental" },
  { odooModel: "sped.produto", mode: "incremental" },
  { odooModel: "sped.produto.controle", mode: "incremental" },
  { odooModel: "sped.produto.familia", mode: "incremental" },
  { odooModel: "sped.produto.lista.material", mode: "incremental" },
  { odooModel: "sped.produto.lista.material.item", mode: "incremental" },
  { odooModel: "sped.produto.lista.material.processo", mode: "incremental" },
  { odooModel: "sped.produto.lote.serie", mode: "incremental" },
  { odooModel: "sped.produto.marca", mode: "incremental" },
  { odooModel: "sped.produto.tipo", mode: "incremental" },
  { odooModel: "sped.produto.variante", mode: "estatico" },
  { odooModel: "sped.produto.volume", mode: "incremental" },
  { odooModel: "sped.usuario", mode: "incremental" },
  { odooModel: "sped.usuario.departamento", mode: "incremental" },
  { odooModel: "sped.usuario.perfil", mode: "incremental" },
  { odooModel: "sped.veiculo", mode: "incremental" },
  // F4 L1a — expansão da base de leitura (novo acesso joaozanini)
  { odooModel: "sped.tabela.preco", mode: "incremental" },
  { odooModel: "sped.tabela.preco.regra", mode: "incremental" },
  { odooModel: "sped.servico", mode: "incremental" },
  { odooModel: "sped.apuracao", mode: "incremental" },
  { odooModel: "sped.carta.correcao", mode: "incremental" },
  // F4 L1c — resíduo operacional 4a
  { odooModel: "sped.certificado", mode: "incremental", excludeFields: ["senha", "arquivo"] },
  { odooModel: "finan.baixa.lancamento", mode: "incremental" },
  { odooModel: "pedido.faturamento", mode: "incremental" },
  // F4 L1b — camada de referência (27 tabelas)
  { odooModel: "sped.ncm", mode: "incremental" },
  { odooModel: "sped.cfop", mode: "incremental" },
  { odooModel: "sped.cest", mode: "incremental" },
  { odooModel: "sped.cnae", mode: "incremental" },
  { odooModel: "sped.nbs", mode: "incremental" },
  { odooModel: "sped.natureza.operacao", mode: "incremental" },
  { odooModel: "sped.unidade", mode: "incremental" },
  { odooModel: "sped.cst.icms", mode: "incremental" },
  { odooModel: "sped.cst.icms.sn", mode: "incremental" },
  { odooModel: "sped.cst.ipi", mode: "incremental" },
  { odooModel: "sped.cst.pis.cofins", mode: "incremental" },
  { odooModel: "sped.cst.cibs", mode: "incremental" },
  { odooModel: "sped.municipio", mode: "incremental" },
  { odooModel: "sped.pais", mode: "incremental" },
  { odooModel: "sped.estado", mode: "incremental" },
  { odooModel: "sped.condicao.pagamento", mode: "incremental" },
  { odooModel: "sped.feriado", mode: "incremental" },
  { odooModel: "sped.aliquota.icms.proprio", mode: "incremental" },
  { odooModel: "sped.aliquota.icms.st", mode: "incremental" },
  { odooModel: "sped.aliquota.inss", mode: "incremental" },
  { odooModel: "sped.aliquota.ipi", mode: "incremental" },
  { odooModel: "sped.aliquota.irpf", mode: "incremental" },
  { odooModel: "sped.aliquota.iss", mode: "incremental" },
  { odooModel: "sped.aliquota.pis.cofins", mode: "incremental" },
  { odooModel: "sped.aliquota.simples.aliquota", mode: "incremental" },
  { odooModel: "sped.aliquota.simples.anexo", mode: "incremental" },
  { odooModel: "sped.aliquota.simples.teto", mode: "incremental" },
] as const;

/** Nome da tabela raw de um modelo Odoo: estoque.saldo.hoje -> raw_estoque_saldo_hoje. */
export function rawTableFor(odooModel: string): string {
  return "raw_" + odooModel.replace(/\./g, "_");
}
