// mcp/lib/contrato-lista.data.ts
// Fase B (Nex Especialista) , gate INCREMENTAL do contrato de lista.
//
// Toda tool que retorna lista deve: (1) query com orderBy deterministico,
// (2) declarar `ordenadoPor` no envelope, (3) topMaiores quando monetaria.
// Esta allowlist contem as tools AINDA NAO migradas; o teste de contrato
// (mcp/__tests__/contrato-lista.test.ts) FALHA se uma tool fora dela nao
// declarar ordenadoPor, e FALHA se uma migrada continuar listada (stale).
// Criterio de saida da Fase B: allowlist == [] (padrao TOOLS_SEM_FORMATADOR_REAL).
// Origem: docs/superpowers/research/2026-06-11-auditoria-contrato-lista.md

export const TOOLS_SEM_CONTRATO_DE_LISTA: readonly string[] = [
  "bi_consulta_avancada",
  "cadastro_buscar_parceiro",
  "cadastro_cidades_listar",
  "cadastro_filiais_listar",
  "cadastro_parceiros_novos",
  "cadastro_parceiros_por_cidade",
  "cadastro_parceiros_por_uf",
  "cadastro_parceiros_sem_documento",
  "cadastros.res_partner_category.set_tags",
  "comercial_parcelas_a_vencer",
  "comercial_pedido_historico_etapas",
  "comercial_pedido_travados_por_etapa",
  "comercial_pedidos_atrasados",
  "comercial_pedidos_listar_top_valor",
  "comercial_pedidos_por_etapa",
  "comercial_pedidos_por_uf",
  "comercial_pedidos_por_vendedor",
  "comercial_pedidos_sem_vendedor",
  "comercial_produtos_por_familia",
  "comercial_produtos_por_margem",
  "comercial_vendedores_cadastrados",
  "contabil_centro_custo",
  "contabil_conta_referencial",
  "contabil_estrutura_conta",
  "contabil_movimento_conta",
  "contabil_plano_de_contas",
  "contabil_resultado_por_natureza",
  "contabil_saldo_conta",
  "estoque_concentracao",
  "estoque_entradas_saidas",
  "estoque_locais_por_produto",
  "estoque_produtos_parados",
  "estoque_produtos_saldo_zero",
  "estoque_saldo_produto",
  "estoque_top_movimentados",
  "estoque_valor_armazem",
  "fiscal_apuracao",
  "fiscal_carta_correcao",
  "fiscal_certificados",
  "fiscal_dfe_importados_periodo",
  "fiscal_dfe_pendentes_manifestacao",
  "fiscal_dfe_por_fornecedor",
  "fiscal_faturamento_mensal_serie",
  "fiscal_faturamento_nao_autorizado",
  "fiscal_faturamento_por_cfop",
  "fiscal_faturamento_por_cliente",
  "fiscal_faturamento_por_empresa",
  "fiscal_faturamento_por_marca",
  "fiscal_faturamento_por_operacao",
  "fiscal_faturamento_por_regime",
  "fiscal_faturamento_por_uf",
  "fiscal_intercompany",
  "fiscal_mdfe_manifestos",
  "fiscal_notas_emitidas",
  "fiscal_notas_emitidas_por_cliente",
  "fiscal_notas_emitidas_por_produto",
  "fiscal_notas_recebidas",
  "fiscal_notas_recebidas_por_fornecedor",
  "fiscal_ponte_faturamento",
  "fiscal_produtos_faturados",
  "fiscal_reinf_eventos",
  "preco_produto",
  "preco_tabela",
  "referencia_buscar",
  "servico_buscar",
  "servico_listar",
];
