// mcp/catalog/tool-triggers.data.ts
// F3 onda 3a (task 3a.1b): frases-gatilho pt-br por tool.id, curadas por dominio
// a partir das perguntas-ouro [OK] do dossie (workflow Opus wa46iq9bv). 92 read-tools.
// Fonte do vetor de retrieval (embeddingTextFor) e enriquece a description do LLM.

export const TOOL_TRIGGERS: Record<string, string[]> = {
  "cadastro_buscar_parceiro": ["qual e o cliente chamado fulano", "achar o fornecedor pelo nome", "qual o cnpj da empresa tal", "procurar parceiro por nome ou cpf"],
  "cadastro_cidades_listar": ["quais cidades temos parceiros", "lista de cidades com clientes", "temos parceiros em campinas", "cidades de sp no cadastro"],
  "cadastro_contar_parceiros": ["quantos clientes temos", "quantos fornecedores cadastrados", "quantos parceiros inativos ou desativados", "comparacao de clientes versus fornecedores"],
  "cadastro_detalhar_parceiro": ["cadastro completo do cliente", "qual o email e telefone do cliente fulano", "ficha completa do parceiro", "endereco e dados do cliente"],
  "cadastro_detalhar_produto": ["qual o preco do produto", "ficha tecnica completa do produto", "ncm e codigo de barras do item", "detalhe do produto marca e familia"],
  "cadastro_filiais_listar": ["quantas filiais temos", "quais empresas do grupo", "qual o cnpj da matriz", "filiais ativas em sp"],
  "cadastro_parceiros_novos": ["parceiros cadastrados esta semana", "clientes novos esse mes", "quem cadastramos ontem", "novos parceiros no periodo"],
  "cadastro_parceiros_por_cidade": ["quantos clientes em cada cidade", "top 10 cidades com mais clientes", "parceiros do interior de sao paulo", "clientes da capital"],
  "cadastro_parceiros_por_uf": ["quantos clientes por estado", "distribuicao geografica de clientes por uf", "qual uf concentra mais clientes", "ranking de estados por quantidade de parceiros"],
  "cadastro_parceiros_sem_documento": ["parceiros sem cnpj ou cpf", "clientes sem documento cadastrado", "cadastros incompletos para auditoria", "quem esta sem documento"],
  "comercial_comissoes": ["qual a comissao do vendedor Joao", "qual o total de comissoes a pagar", "comissao do pedido", "comissoes por vendedor"],
  "comercial_contar_pedidos": ["quantos pedidos temos cadastrados", "numero total de pedidos", "quantidade de pedidos no sistema", "total de pedidos cadastrados"],
  "comercial_cotacoes": ["quais cotacoes estao abertas", "quantas cotacoes de venda temos", "lista de propostas comerciais", "cotacoes de compra e venda"],
  "comercial_parcelas_a_vencer": ["quais parcelas vencem nos proximos 30 dias", "quanto temos a receber no proximo mes", "parcelas a vencer", "valor total a receber em breve"],
  "comercial_pedido_historico_etapas": ["quanto tempo o pedido 123 ficou em cada etapa", "qual etapa do pedido demorou mais", "tem retrabalho no pedido", "quantas vezes o pedido passou pela etapa preparacao"],
  "comercial_pedido_travados_por_etapa": ["quais pedidos estao travados no fluxo", "pedidos parados ha mais de 60 dias", "qual o pedido mais antigo travado numa etapa", "pedidos sem avancar de etapa"],
  "comercial_pedidos_atrasados": ["quais parcelas estao vencidas", "valor total de parcelas atrasadas", "quantas parcelas estao em atraso", "quais clientes tem parcelas vencidas"],
  "comercial_pedidos_listar_top_valor": ["qual o pedido com maior valor", "lista os top 10 pedidos por valor", "qual o pedido mais antigo em aberto", "pedidos do cliente Smartfit"],
  "comercial_pedidos_periodo": ["quantos pedidos foram feitos em janeiro de 2026", "valor total de pedidos no mes", "pedidos do periodo", "faturamento de pedidos entre duas datas"],
  "comercial_pedidos_por_etapa": ["como estao distribuidos os pedidos por etapa", "quantos pedidos em aberto e quantos fechados", "valor total de pedidos em aberto", "quantos pedidos foram cancelados"],
  "comercial_pedidos_por_uf": ["como estao distribuidos os pedidos por estado", "qual estado tem mais pedidos", "qual UF fatura mais", "valor total de pedidos em SP"],
  "comercial_pedidos_por_vendedor": ["ranking de vendedores por quantidade de pedidos", "qual vendedor vendeu mais", "ticket medio por vendedor", "vendas por vendedor no periodo"],
  "comercial_pedidos_sem_vendedor": ["quais pedidos nao tem vendedor atribuido", "pedidos orfaos sem responsavel", "quantos pedidos estao sem vendedor", "valor total de pedidos sem vendedor"],
  "comercial_produtos_por_familia": ["produtos da familia Life Fitness", "quantas familias de produtos temos", "qual a familia com mais produtos", "quantos produtos temos no cadastro"],
  "comercial_produtos_por_margem": ["qual produto tem maior margem", "qual a margem de um produto", "produtos com menor margem", "produtos sem preco cadastrado"],
  "comercial_tempo_medio_fechamento": ["qual o tempo medio de fechamento de um pedido", "quanto tempo leva pra fechar uma venda", "mediana de tempo de fechamento", "tempo minimo e maximo para concluir pedido"],
  "comercial_vendedores_cadastrados": ["quantos vendedores temos", "lista todos os vendedores cadastrados", "quais sao os vendedores", "relacao de vendedores"],
  "contabil_centro_custo": ["qual e o saldo por centro de custo no periodo", "quantos centros de custo temos com movimentacao", "qual centro tem maior custo", "resultado por centro de custo"],
  "contabil_conta_referencial": ["qual e o plano referencial sped completo", "mostre as contas de ativo no referencial natureza 01", "procure uma conta referencial por codigo ou nome", "de-para padronizado da receita federal por natureza"],
  "contabil_detalhar_conta": ["detalhe completo de uma conta contabil", "me mostre tudo sobre essa conta pelo id", "natureza e nivel da conta com caminho hierarquico", "dados da conta tipo e conta pai"],
  "contabil_estrutura_conta": ["me mostre a hierarquia da conta 1.01.01", "qual e a conta pai dessa conta", "quais sao as contas filhas dessa conta", "a conta X e sintetica ou analitica"],
  "contabil_movimento_conta": ["mostre o razao de uma conta com todas as partidas", "quantas partidas tem a conta X", "movimentos de uma conta em um intervalo de datas", "historico dos lancamentos da conta no periodo"],
  "contabil_plano_de_contas": ["qual e o plano de contas completo da matrix", "quantas contas temos no plano contabil", "procure contas com impostos no nome", "lista de contas contabeis por codigo ou nome"],
  "contabil_resultado_por_natureza": ["qual foi o resultado do periodo receita menos despesa", "qual foi a receita e a despesa total", "tivemos lucro ou prejuizo no periodo", "mostre receita vs despesa por natureza"],
  "contabil_saldo_conta": ["qual e o saldo de uma conta no periodo", "me mostre o balancete de todas as contas", "saldo liquido debito menos credito da conta", "total de debitos e creditos no periodo"],
  "estoque_concentracao": ["qual a concentracao de valor do estoque por familia", "curva ABC do estoque por marca", "quanto do estoque se concentra em poucas familias", "analise pareto do valor de estoque"],
  "estoque_entradas_saidas": ["qual foi a entrada e saida de estoque no mes", "movimentacao mensal de estoque dos ultimos 12 meses", "serie historica de entradas e saidas", "quanto entrou e saiu de estoque no periodo"],
  "estoque_locais_por_produto": ["em quais armazens esta o produto X", "onde esta o saldo desse item por local", "quantos depositos tem esse produto e o saldo de cada um", "localizacoes de um produto no estoque"],
  "estoque_minimo_maximo": ["quais os parametros de estoque minimo e maximo cadastrados", "tem algum minimo e maximo de reabastecimento por produto", "produtos abaixo do minimo cadastrado", "niveis de ressuprimento configurados no estoque"],
  "estoque_produtos_parados": ["quais produtos estao parados em estoque", "itens sem movimento ha mais de 60 dias", "qual o valor do estoque parado e imobilizado", "produtos encalhados com saldo positivo e baixo giro"],
  "estoque_produtos_saldo_zero": ["quantos produtos estao com saldo zerado", "quais itens estao zerados no estoque hoje", "produtos sem saldo e produtos negativos", "contagem de produtos esgotados em estoque"],
  "estoque_saldo_produto": ["qual o saldo do produto X hoje", "quantas unidades temos desse produto em estoque", "qual o saldo total de estoque em unidades e valor", "estoque atual do produto Y por nome ou codigo"],
  "estoque_top_movimentados": ["quais produtos foram mais movimentados no periodo", "top produtos com maior volume de movimentacao", "ranking dos itens que mais giraram em valor", "produtos com maior movimentacao de estoque"],
  "estoque_valor_armazem": ["qual o valor total do estoque a custo", "valor de estoque por armazem", "quanto vale o estoque parado em cada deposito", "posicao financeira do estoque a preco de custo", "valor de estoque apenas fisico", "valor de estoque em demonstracao", "estoque em poder de terceiros", "valor de estoque filtrado por locais"],
  "financeiro_baixas_cobranca": ["quantos pagamentos foram processados no periodo", "baixas de cobranca bancaria recebidas", "pagamentos recebidos via retorno do banco", "boletos baixados com juros multa e desconto"],
  "financeiro_caixa_periodo": ["quanto entrou e quanto saiu no mes", "movimentacao de caixa no periodo", "entradas e saidas de caixa realizado", "saldo de caixa entre essas datas"],
  "financeiro_carteiras_cobranca": ["qual carteira de cobranca usamos", "configuracao de boleto por banco", "carteiras de cobranca cadastradas", "beneficiario e convenio das carteiras"],
  "financeiro_cheques": ["cheques emitidos pendentes ou compensados", "lista de cheques no periodo", "valor e banco dos cheques", "cheques como forma de pagamento"],
  "financeiro_contas_a_pagar": ["quanto devemos aos fornecedores", "total a pagar em aberto", "quais fornecedores temos titulo aberto", "maior fornecedor por volume pendente"],
  "financeiro_contas_a_receber": ["quanto os clientes nos devem", "total a receber em aberto", "quais clientes tem titulo em aberto", "contas a receber dos clientes"],
  "financeiro_fluxo_caixa": ["fluxo de caixa mensal", "fluxo realizado versus previsto", "serie do fluxo de caixa ao longo dos meses", "qual a diferenca entre previsto e realizado de caixa"],
  "financeiro_liquidez": ["qual o indice de liquidez da empresa", "consigo pagar tudo com o caixa de hoje", "liquidez imediata e liquidez corrente", "como esta a saude financeira de curto prazo"],
  "financeiro_pix_recebidos": ["pix enviados e recebidos no periodo", "transacoes pix com tarifas", "recebimentos via pix", "status dos pix no periodo"],
  "financeiro_remessas_geradas": ["que remessas enviamos ao banco no periodo", "arquivos de remessa bancaria gerados", "remessas enviadas e confirmadas pelo banco", "envios de cobranca para o banco"],
  "financeiro_resultado_por_conta": ["receita versus despesa no periodo", "qual conta teve a maior despesa", "qual conta teve a maior receita", "dre gerencial por conta"],
  "financeiro_retornos_processados": ["que retornos bancarios recebemos no periodo", "arquivos de retorno processados do banco", "totais de entrada e saida dos retornos bancarios", "retornos do banco com saldo no periodo"],
  "financeiro_saldo_contas": ["qual o saldo em caixa e nos bancos hoje", "quanto temos disponivel em conta", "saldo por banco e conta", "estamos com caixa positivo ou negativo"],
  "financeiro_titulos_vencidos": ["quanto esta vencido e nao pago", "titulos em atraso de clientes e fornecedores", "quanto esta vencido para pagar", "boletos vencidos com dias de atraso"],
  "fiscal_apuracao": ["qual a apuracao fiscal de janeiro", "valores a recolher de ICMS PIS e COFINS", "apuracao de ICMS IPI PIS COFINS do periodo", "saldo credor de ICMS e apuracao entregue"],
  "fiscal_carta_correcao": ["ha cartas de correcao em aberto", "quais CCe foram emitidas", "cartas de correcao de uma nota", "correcoes fiscais registradas no periodo"],
  "fiscal_certificados": ["qual certificado digital expira primeiro", "status do certificado A1", "validade dos certificados eCNPJ", "certificados digitais perto de vencer"],
  "fiscal_contar_notas": ["quantas notas fiscais existem no total", "numero total de notas emitidas e recebidas", "contagem de notas de entrada e saida", "quantas NF temos cadastradas"],
  "fiscal_detalhar_nota": ["detalhe completo de uma nota fiscal", "abrir os dados de uma NF especifica", "ver chave serie e participante de uma nota", "informacoes de uma nota pelo id"],
  "fiscal_dfe_importados_periodo": ["quantos DFe entraram em maio", "quais DFe de fornecedores chegaram no periodo", "notas eletronicas importadas via manifestacao", "documentos fiscais capturados no periodo"],
  "fiscal_dfe_pendentes_manifestacao": ["quais DFe estao sem manifestacao", "notas de fornecedor a manifestar", "DFe pendentes de ciencia ou confirmacao", "documentos fiscais aguardando manifestacao do destinatario"],
  "fiscal_dfe_por_fornecedor": ["qual fornecedor enviou mais DFe", "de quais fornecedores chegaram DFe", "DFe agrupados por fornecedor", "quantas notas eletronicas do fornecedor X recebemos"],
  "fiscal_faturamento_mensal_serie": ["qual a serie de faturamento dos ultimos 12 meses", "faturamento mes a mes esse ano", "comparativo mensal de faturamento", "evolucao do faturamento por mes"],
  "fiscal_faturamento_nao_autorizado": ["quais notas estao sem autorizacao", "notas denegadas rejeitadas ou em processamento", "faturamento de notas nao autorizadas", "notas de saida que nao foram autorizadas nem canceladas"],
  "fiscal_faturamento_periodo": ["quanto faturamos no periodo", "qual foi o faturamento desse mes", "total de notas de saida autorizadas e valor faturado", "receita de vendas entre tais datas"],
  "fiscal_faturamento_por_cfop": ["qual CFOP e mais usado nas saidas", "faturamento por CFOP", "vendas agrupadas por codigo fiscal de operacao", "valor faturado por CFOP", "faturamento por operacao fiscal", "composicao do faturamento", "quanto e venda servico transferencia devolucao", "faturamento por categoria", "separar receita de transferencia e remessa"],
  "fiscal_receita_consolidada": ["faturamento real", "receita consolidada", "quanto vendemos para fora do grupo", "receita sem intercompany", "faturamento do grupo eliminando intercompany", "sem contar vendas entre empresas do grupo", "receita externa do grupo"],
  "fiscal_intercompany": ["vendas entre empresas do grupo", "intercompany", "quanto uma empresa vende para outra do grupo", "matriz de transferencias intragrupo", "vendas intragrupo"],
  "fiscal_ponte_faturamento": ["reconcilie o faturamento", "como chegou na receita externa", "ponte do faturamento", "do bruto ao liquido", "do faturamento bruto a receita real", "waterfall do faturamento", "explique a diferenca entre faturamento e receita"],
  "fiscal_margem_aproximada": ["margem bruta", "margem das vendas", "qual a margem", "receita menos custo", "margem aproximada", "lucro bruto aproximado", "quanto sobra depois do custo do produto"],
  "fiscal_faturamento_por_regime": ["faturamento por regime tributario", "faturamento por regime", "quanto cada regime faturou", "faturamento das empresas do simples nacional", "faturamento do lucro real e do presumido", "receita por regime tributario", "quanto fatura o simples e quanto o lucro real", "vendas por enquadramento tributario"],
  "fiscal_faturamento_por_cliente": ["qual cliente foi o maior faturamento no periodo", "top 10 clientes por faturamento", "ranking de clientes que mais compraram", "faturamento agrupado por cliente"],
  "fiscal_faturamento_por_empresa": ["qual filial faturou mais", "faturamento por empresa do grupo", "comparativo de vendas entre filiais", "faturamento de cada empresa do grupo"],
  "fiscal_faturamento_por_marca": ["qual marca de produto teve maior faturamento", "faturamento por marca", "qual marca vende mais", "top marcas em valor faturado"],
  "fiscal_faturamento_por_operacao": ["qual a natureza de operacao mais usada nas vendas", "faturamento por natureza de operacao", "quantas operacoes de devolucao tivemos", "faturamento separando venda de nao-venda"],
  "fiscal_faturamento_por_uf": ["como varia o faturamento por estado", "faturamento por UF", "vendas por regiao do pais", "faturamento por estado do cliente"],
  "fiscal_demonstracoes": ["faturamento de operacoes de demonstracao", "remessas para demonstracao por uf", "quantas notas de demonstracao emitimos", "equipamentos enviados para demonstracao", "quanto retornou de demonstracao", "demonstracoes por empresa"],
  "fiscal_vendas_produto_por_empresa": ["venda do produto por empresa", "quanto vendemos de esteira por empresa e qual o cmv", "cmv do produto", "vendas e custo da mercadoria vendida por empresa"],
  "fiscal_faturamento_recebido": ["quanto do faturamento ja foi pago", "faturamento recebido versus a receber", "valor faturado que entrou no caixa", "receita paga e em aberto por pedido"],
  "fiscal_impostos_periodo": ["qual foi o ICMS total do periodo", "total de impostos estimados IBPT", "carga de ICMS proprio no periodo", "estimativa de impostos das notas"],
  "fiscal_mdfe_manifestos": ["quais manifestos de transporte estao abertos", "MDFe do periodo", "manifestos de carga e descarga", "status dos manifestos eletronicos de documentos fiscais"],
  "fiscal_notas_emitidas": ["quais notas foram emitidas em janeiro", "lista de notas fiscais de saida do periodo", "notas autorizadas que temos", "notas canceladas em 2026", "notas rejeitadas ou denegadas"],
  "fiscal_notas_emitidas_por_cliente": ["quais notas foram emitidas para o cliente smartfit", "NF do cliente X esse mes", "notas de saida de um cliente especifico", "notas emitidas para tal cliente"],
  "fiscal_notas_emitidas_por_produto": ["quais notas contem o produto haltere 10kg", "notas que sairam de um produto especifico", "em quais NF aparece esse produto", "rastrear produto nas notas de saida"],
  "fiscal_notas_recebidas": ["quanto compramos no periodo", "notas fiscais de entrada recebidas", "notas de compras e devolucoes que recebemos", "valor total das notas de entrada"],
  "fiscal_notas_recebidas_por_fornecedor": ["qual e o maior fornecedor por valor de compras", "quantas notas recebemos do fornecedor X", "notas de entrada agrupadas por fornecedor", "ranking de fornecedores por compras"],
  "fiscal_produtos_faturados": ["qual foi o produto mais vendido em valor", "produtos mais faturados", "quantos produtos diferentes faturamos", "mix de vendas por produto"],
  "fiscal_reinf_eventos": ["ha eventos de retencao pendentes de declaracao", "eventos REINF do periodo", "obrigacao acessoria REINF R-4020 R-2010", "status de transmissao dos eventos REINF"],
  "preco_contar_regras": ["quantas regras de preco temos", "numero total de regras de preco cadastradas", "total de regras nas tabelas de preco"],
  "preco_produto": ["qual o preco do produto ABC", "quais tabelas tem o produto", "regras de preco de um produto", "preco e vigencia do produto"],
  "preco_tabela": ["regras de uma tabela de preco especifica", "qual a regra de preco da familia acessorios na tabela padrao", "lista as regras da tabela de preco", "precos cadastrados nesta tabela"],
  "referencia_buscar": ["qual e o CFOP para venda intra-estado", "buscar NCM CFOP CEST CNAE na tabela de referencia", "consultar codigo fiscal ou natureza de operacao", "qual a NCM ou CST de tal codigo"],
  "servico_buscar": ["qual e o servico tal", "buscar servico por codigo ou descricao", "qual a aliquota de inss retido do servico", "achar servico no catalogo fiscal"],
  "servico_contar": ["quantos servicos cadastrados", "total de servicos no catalogo", "numero de servicos existentes"],
  "servico_listar": ["listar todos os servicos", "panorama do catalogo de servicos", "quais servicos temos cadastrados", "catalogo de servicos fiscais"],
};